variables:
  DB_NUM: 4
  TB_NUM: 32

shardingTableRule:
  templates:
    sdst-proj-1:
      actualDataNodes: ds\${0..${DB_NUM - 1}}.${TABLE}\${0..${TB_NUM - 1}}
      databaseStrategy:
        inline:
          shardingColumn: ${DB_COLUMN}
          algorithmExpression: ds\${${DB_COLUMN} % ${DB_NUM}}
      tableStrategy:
        inline:
          shardingColumn: ${TB_COLUMN}
          algorithmExpression: ${TABLE}\${Long.valueOf(${TB_COLUMN}) % ${TB_NUM}}
    sdst-proj-2:
      actualDataNodes: ds\${0..${DB_NUM - 1}}.${TABLE}
      databaseStrategy:
        inline:
          shardingColumn: ${DB_COLUMN}
          algorithmExpression: ds\${${DB_COLUMN} % ${DB_NUM}}
    sdst-proj-3:
      actualDataNodes: ds\${0..${DB_NUM - 1}}.${TABLE}
      databaseStrategy:
        inline:
          shardingColumn: ${DB_COLUMN}
          algorithmExpression: ds\${Math.abs(${DB_COLUMN}.hashCode()) % ${DB_NUM}}
    sdst-proj-4:
      actualDataNodes: ds0.${TABLE}\${0..11}
      tableStrategy:
        inline:
          shardingColumn: ${TB_COLUMN}
          algorithmExpression: ${TABLE}\${(${TB_COLUMN} - 1) % 12}
    sdst-proj-5:
      actualDataNodes: ds0.${TABLE}\${0..30}
      tableStrategy:
        inline:
          shardingColumn: ${TB_COLUMN}
          algorithmExpression: ${TABLE}\${(${TB_COLUMN} - 1) % 31}
  usages:
    sdst-proj-1:
      - ACCT|ROUTING_ID|CUST_ID
      - ACCT_ATTR_VALUE|ROUTING_ID|CUST_ID
      - ACCT_DELIVER_METHOD|ROUTING_ID|CUST_ID
      - ACCT_UPP_INST|ROUTING_ID|CUST_ID
      - ACCT_UPP_INST_VALUE|ROUTING_ID|CUST_ID
      - BAL_SHARE|ROUTING_ID|CUST_ID
      - BAL_SHARE_DETAIL|ROUTING_ID|CUST_ID
      - BIZ_CUST|ROUTING_ID|CUST_ID
      - CONTACT_MAN|ROUTING_ID|CUST_ID
      - CONTACT_MAN_ATTR_VALUE|ROUTING_ID|CUST_ID
      - CUST|ROUTING_ID|CUST_ID
      - CUST_ATTR_VALUE|ROUTING_ID|CUST_ID
      - CUST_CONTACT|ROUTING_ID|CUST_ID
      - CUST_SPECIAL_GROUP|ROUTING_ID|CUST_ID
      - SUBS_SPECIAL_GROUP|ROUTING_ID|CUST_ID
      - SUBS_SPECIAL_GROUP_HIS|ROUTING_ID|CUST_ID
      - FELLOW_NBR|ROUTING_ID|CUST_ID
      - PROD|ROUTING_ID|CUST_ID
      - PROD_ATTR_VALUE|ROUTING_ID|CUST_ID
      - PROD_INDIVIDUAL_LIFECYCLE|ROUTING_ID|CUST_ID
      - PROD_STATE_CHANGE_LOG|ROUTING_ID|CUST_ID
      - SUBS|ROUTING_ID|CUST_ID
      - SUBS_GOODS_INST|ROUTING_ID|CUST_ID
      - SUBS_GOODS_INST_ATTR|ROUTING_ID|CUST_ID
      - SUBS_HOME_CELL|ROUTING_ID|CUST_ID
      - SUBS_HOME_ZONE|ROUTING_ID|CUST_ID
      - SUBS_UPP_INST|ROUTING_ID|CUST_ID
      - SUBS_UPP_INST_VALUE|ROUTING_ID|CUST_ID
      - USED_RES|ROUTING_ID|CUST_ID
      - BC_MEMBER|ROUTING_ID|CUST_ID
      - BC_MEMBER_HIS|ROUTING_ID|CUST_ID
      - BC_ROLE_INST|ROUTING_ID|CUST_ID
      - BC_ROLE_INST_HIS|ROUTING_ID|CUST_ID
      - MEMBER_WORK_HOUR|ROUTING_ID|CUST_ID
      - ACCT_HIS|ROUTING_ID|CUST_ID
      - ACCT_ATTR_VALUE_HIS|ROUTING_ID|CUST_ID
      - ACCT_UPP_INST_HIS|ROUTING_ID|CUST_ID
      - ACCT_UPP_INST_VALUE_HIS|ROUTING_ID|CUST_ID
      - BIZ_CUST_HIS|ROUTING_ID|CUST_ID
      - CONTACT_MAN_HIS|ROUTING_ID|CUST_ID
      - CUST_HIS|ROUTING_ID|CUST_ID
      - CUST_ATTR_VALUE_HIS|ROUTING_ID|CUST_ID
      - CUST_SPECIAL_GROUP_HIS|ROUTING_ID|CUST_ID
      - FELLOW_NBR_HIS|ROUTING_ID|CUST_ID
      - PROD_HIS|ROUTING_ID|CUST_ID
      - PROD_ATTR_VALUE_HIS|ROUTING_ID|CUST_ID
      - SUBS_HIS|ROUTING_ID|CUST_ID
      - SUBS_GOODS_INST_HIS|ROUTING_ID|CUST_ID
      - SUBS_GOODS_INST_ATTR_HIS|ROUTING_ID|CUST_ID
      - SUBS_UPP_INST_HIS|ROUTING_ID|CUST_ID
      - SUBS_UPP_INST_VALUE_HIS|ROUTING_ID|CUST_ID
      - BC_BUSINESS_HOUR|ROUTING_ID|CUST_ID
      - CUST_HABIT|ROUTING_ID|CUST_ID
      - SPC_BAL_SHARE|ROUTING_ID|CUST_ID
      - CUST_DELIVERY_ADDRESS|ROUTING_ID|CUST_ID
      - CONTRACT_ITEM_OFFER_ATTR|ROUTING_ID|CUST_ID
      - CONTRACT_ITEM_OFFER_ATTR_VAL|ROUTING_ID|CUST_ID
      - CUST_CONTRACT|ROUTING_ID|CUST_ID
      - CUST_CONTRACT_ITEM|ROUTING_ID|CUST_ID
      - CUST_CONTRACT_ITEM_SUBS|ROUTING_ID|CUST_ID
      - CUST_CONTRACT_ITEM_SUBS_HIS|ROUTING_ID|CUST_ID
      - CUST_CONTRACT_ITEM_ACCT|ROUTING_ID|CUST_ID
      - CUST_CONTRACT_ITEM_ACCT_HIS|ROUTING_ID|CUST_ID
      - CUST_CONTRACT_ITEM_SUBS_RELA|ROUTING_ID|CUST_ID
      - CUST_PRICE_BOOK_HANDSET|ROUTING_ID|CUST_ID
      - CUST_PRICE_BOOK_HANDSET_REBATE|ROUTING_ID|CUST_ID
      - CUST_PRICE_BOOK_OTC_BENEFIT|ROUTING_ID|CUST_ID
      - CUST_PRICE_BOOK_OTC_RATE|ROUTING_ID|CUST_ID
      - CUST_PRICE_BOOK_PRICE_PLAN|ROUTING_ID|CUST_ID
      - CUST_PRICE_BOOK_S_PARAM_VALUE|ROUTING_ID|CUST_ID
      - CUST_PRICE_BOOK_VER|ROUTING_ID|CUST_ID
      - CUST_PRICE_PLAN_T_PARAM|ROUTING_ID|CUST_ID
      - CUST_PRICE_PLAN_T_PARAM_VALUE|ROUTING_ID|CUST_ID
      - CUST_PRICE_P_T_PARAM_CATEGORY|ROUTING_ID|CUST_ID
      - CONTRACT_ITEM_ATTR_VAL|ROUTING_ID|CUST_ID
      - CONTRACT_ATTR_VAL|ROUTING_ID|CUST_ID      
      - AGREEMENT_INST|ROUTING_ID|CUST_ID
      - AGREEMENT_OBJ_INST|ROUTING_ID|CUST_ID
      - AGREEMENT_INST_HIS|ROUTING_ID|CUST_ID
      - CC_ACCT_HIS|ROUTING_ID|CUST_ID
      - OFFER_PROD_INST_RELA|ROUTING_ID|CUST_ID
      - OFFER_PROD_INST_RELA_HIS|ROUTING_ID|CUST_ID
      - CUST_DOC|ROUTING_ID|CUST_ID      
      - BANK_ACCT|ROUTING_ID|CUST_ID
      - CREDIT_CARD|ROUTING_ID|CUST_ID
      - CUST_SOCIAL_NBR|ROUTING_ID|CUST_ID
      - DUNNING_AS_GROUP|ROUTING_ID|CUST_ID
      - DUNNING_AS_GROUP_HIS|ROUTING_ID|PART_ID
      - DUNNING_AS_GROUP_MEM_HIS|ROUTING_ID|PART_ID
      - DUNNING_AS_GROUP_MEM|ROUTING_ID|CUST_ID
      - MANDATE|ROUTING_ID|CUST_ID
      - MANDATE_HIS|ROUTING_ID|CUST_ID
      - PAYMENT_PROFILE|ROUTING_ID|CUST_ID 
      
      # 以下四个表因为开发代码未改，临时先加上
      - ALL_CUST|ROUTING_ID|CUST_ID
      - ALL_ACCT|ROUTING_ID|CUST_ID 
      - ALL_SUBS|ROUTING_ID|CUST_ID
      - ALL_BC_MEMBER|ROUTING_ID|CUST_ID    
    sdst-proj-2:
      - CERT|ROUTING_ID
      - CUST_BILL_DELIVERY_INFO|ROUTING_ID
      - CUST_IMAGE|ROUTING_ID
      - MANAGER_CONTACT_MAN|ROUTING_ID
      - CERT_HIS|ROUTING_ID
      - CUST_BILL_DELIVERY_INFO_HIS|ROUTING_ID
      - MANAGER_CONTACT_MAN_HIS|ROUTING_ID 
    sdst-proj-3:
      - ACCT_IDENTIFY|IDENTIFY_VALUE
      - CUST_IDENTIFY|IDENTIFY_VALUE
      - SUBS_IDENTIFY|IDENTIFY_VALUE
      - SUBS_IDENTIFY_HIS|IDENTIFY_VALUE
    sdst-proj-4:
      - SPC_SUBS_UPP_INST_RELA_HIS||PART_ID
      - SPC_BAL_SHARE_HIS||PART_ID
      - SPC_CC_SUBS_HIS||PART_ID
      - SPC_CC_ACCT_HIS||PART_ID
      - SPC_SUBS_HOME_ZONE_HIS||PART_ID
      - SPC_USED_RES_HIS||PART_ID
      - NEW_NP_DB_HIS||PART_ID
    sdst-proj-5:
      - BILL_SPC_ERROR_MESSAGE_HIS||PART_ID 
      
shardingRule:
  defaultDatabaseStrategy:
    hint:
      algorithmClassName: com.iwhalecloud.zdaas.jdbc.hint.NameDataBaseHintShardingAlgorithm
  defaultDataSourceName: ds0
  bindingTables:
    - ALL_CUST,ALL_ACCT,ALL_SUBS,ALL_BC_MEMBER,ACCT,ACCT_ATTR_VALUE,ACCT_DELIVER_METHOD,ACCT_UPP_INST,ACCT_UPP_INST_VALUE,BIZ_CUST,CUST,CUST_ATTR_VALUE,CUST_CONTACT,CUST_SPECIAL_GROUP,FELLOW_NBR,PROD,PROD_ATTR_VALUE,PROD_INDIVIDUAL_LIFECYCLE,PROD_STATE_CHANGE_LOG,SUBS,SUBS_GOODS_INST,SUBS_GOODS_INST_ATTR,SUBS_HOME_CELL,SUBS_HOME_ZONE,SUBS_UPP_INST,SUBS_UPP_INST_VALUE,USED_RES,BC_MEMBER,BC_MEMBER_HIS,BC_ROLE_INST,BC_ROLE_INST_HIS,MEMBER_WORK_HOUR,ACCT_HIS,ACCT_ATTR_VALUE_HIS,ACCT_UPP_INST_HIS,ACCT_UPP_INST_VALUE_HIS,BIZ_CUST_HIS,CUST_HIS,CUST_ATTR_VALUE_HIS,CUST_SPECIAL_GROUP_HIS,FELLOW_NBR_HIS,PROD_HIS,PROD_ATTR_VALUE_HIS,SUBS_HIS,SUBS_GOODS_INST_HIS,SUBS_UPP_INST_HIS,SUBS_UPP_INST_VALUE_HIS,SUBS_SPECIAL_GROUP,SUBS_SPECIAL_GROUP_HIS,BC_BUSINESS_HOUR,CUST_HABIT,CONTACT_MAN,CONTACT_MAN_ATTR_VALUE,CONTACT_MAN_HIS,CUST_DELIVERY_ADDRESS,AGREEMENT_INST
    - SUBS_IDENTIFY,SUBS_IDENTIFY_HIS
    - CONTRACT_ITEM_OFFER_ATTR,CONTRACT_ITEM_OFFER_ATTR_VAL,CUST_CONTRACT,CUST_CONTRACT_ITEM,CUST_CONTRACT_ITEM_SUBS,CUST_CONTRACT_ITEM_SUBS_HIS,CUST_CONTRACT_ITEM_ACCT,CUST_CONTRACT_ITEM_ACCT_HIS,CUST_CONTRACT_ITEM_SUBS_RELA,CUST_PRICE_BOOK_HANDSET,CUST_PRICE_BOOK_HANDSET_REBATE,CUST_PRICE_BOOK_OTC_BENEFIT,CUST_PRICE_BOOK_OTC_RATE,CUST_PRICE_BOOK_PRICE_PLAN,CUST_PRICE_BOOK_S_PARAM_VALUE,CUST_PRICE_BOOK_VER,CUST_PRICE_PLAN_T_PARAM,CUST_PRICE_PLAN_T_PARAM_VALUE
  broadcastTables:
    - ACCT_ATTR
    - ATTR
    - BILLING_CYCLE_TYPE
    - BIND_TYPE
    - BIND_TYPE_ATTR
    - CC_TYPE
    - CERT_TYPE
    - CONTACT_CHANNEL
    - CHANNEL_TYPE
    - CONTACT_MAN_TYPE
    - CUST_CREDIT_GRADE
    - CUST_TYPE
    - CUST_TYPE_ATTR
    - DELIVER_METHOD
    - DOMAIN
    - FELLOW_NBR_TYPE
    - HABIT_TYPE
    - IMP_GRADE
    - INDUSTRY
    - OCCUPATION
    - PROD_STATE
    - PROD_STD_STATE
    - RELIGION
    - SERVICE_BC
    - SPECIAL_GROUP_TYPE
    - TITLE
    - BLACKLIST_TYPE
    - LIFECYCLE_APPLY
    - PROD_EVENT_DIAGRAM
    - CUST_RT_TABLE_TYPE
    - HOME_ZONE
    - GEO_NET_ZONE
    - GEO_HOME_ZONE
    - GEO_HOME_ZONE_CATG
    - GEO_HOME_ZONE_CATG_RLAT
    - ALL_SERV_TYPE
    - BUNDLE_COMPOSE_TYPE
    - BUNDLE_UNIT
    - BUNDLE_UNIT_INDEP_PROD_SPEC
    - BUNDLE_UNIT_SUBS_PLAN
    - CATALOG
    - CATG
    - CPC_BUSINESS_MODULE
    - CPC_CONFIG_ITEM
    - CPC_CONFIG_ITEM_PARAM
    - CPC_DATA_TYPE
    - CPC_DOMAIN
    - CPC_INPUT_TYPE
    - CPC_PROJECT
    - DEPEND_PROD_PACKAGE
    - DEPEND_PROD_SPEC
    - GOODS_PROD_PACKAGE
    - GOODS_PROD_SPEC
    - GROUP_TYPE
    - HOT_SALE_TYPE
    - INDEP_PROD_SPEC
    - NETWORK_TYPE
    - OFFER
    - OFFER_APPLY_AREA
    - OFFER_APPLY_CATG
    - OFFER_APPLY_CHANNEL
    - OFFER_APPLY_ORG
    - OFFER_APPLY_ROLE
    - OFFER_APPLY_STAFF
    - OFFER_ATTR
    - OFFER_CATG
    - OFFER_CATG_APPLY_CHANNEL
    - OFFER_CATG_MEM
    - OFFER_GROUP
    - OFFER_GROUP_MEM
    - OFFER_HOT_SALES
    - OFFER_PRICE_DISPLAY
    - OFFER_RELA
    - OFFER_TYPE
    - OFFER_VER
    - PRICE_PLAN
    - PRICE_PLAN_PACKAGE
    - RELA_TYPE
    - SUBS_PLAN
    - SUBS_PLAN_DIY_RULE
    - SUBS_PLAN_OFFER_ATTR
    - SUBS_PLAN_OFFER_ATTR_VALUE
    - SUBS_PLAN_OFFER_SELECT
    - BASE_ATTR
    - TEXT_ATTR
    - ATTR_GROUP_MEM
    - ATTR_GROUP
    - ATTR_VALUE
    - ATTR_VALUE_LINKAGE  
    - ATTR_TYPE
    - ATTR_DRIVER
    - ATTR_APPLY_CATG
    - ATTR_APPLY_CHANNEL
    - ATTR_CATG
    - OBJ_ATTR
    - ATTR_POPEDIT 
    - BFM_AD_CONFIG
    - BFM_APP
    - BFM_AREA
    - BFM_BULLETIN
    - BFM_BULLETIN_LEVEL
    - BFM_BULLETIN_RECIPIENT
    - BFM_BULLETIN_TMPL
    - BFM_BULLETIN_TYPE
    - BFM_BULLETIN_VIEW
    - BFM_COMPONENT_PRIV
    - BFM_DATA_PRIV
    - BFM_DIR
    - BFM_EVENT_CODE
    - BFM_EVENT_SRC
    - BFM_EVENT_TYPE
    - BFM_GROUP_DATA_PRIV
    - BFM_JOB
    - BFM_JOB_LAYOUT
    - BFM_JOB_ROLE
    - BFM_JOB_USER_GROUP
    - BFM_JOB_WORK_TIME
    - BFM_LAYOUT_DEF
    - BFM_LAYOUT_DEF_HIS
    - BFM_MENU
    - BFM_MENU_DIR
    - BFM_MENU_FAVORITE
    - BFM_MVNO_HIS
    - BFM_ORG
    - BFM_ORG_JOB
    - BFM_ORG_TYPE
    - BFM_ORG_WORK_TIME
    - BFM_PARAMS
    - BFM_PART_SP
    - BFM_PORTAL
    - BFM_PORTAL_BIZ_PARAM
    - BFM_PORTAL_MENU
    - BFM_PORTAL_SP
    - BFM_PORTLETS
    - BFM_PORTLET_SCOPE
    - BFM_PORTLET_TYPE
    - BFM_PRIV
    - BFM_PRIV_TYPE
    - BFM_ROLE
    - BFM_ROLE_DATA_PRIV
    - BFM_ROLE_PORTAL
    - BFM_ROLE_PRIV
    - BFM_SECURITY_RULE
    - BFM_SERV_LOG
    - BFM_STAFF
    - BFM_STAFF_GROUP_LEADER_HIS
    - BFM_STAFF_GROUP_RELA
    - BFM_STAFF_HIS
    - BFM_STAFF_JOB
    - BFM_STAFF_ORG
    - BFM_STAFF_ORG_HIS
    - BFM_STAFF_RELA
    - BFM_STAFF_WORK_TIME
    - BFM_TABLE_EXT
    - BFM_TABLE_EXT_VALUE
    - BFM_USER
    - BFM_USER_DATA_PRIV
    - BFM_USER_GRID
    - BFM_USER_GROUP
    - BFM_USER_GROUP_PRIV
    - BFM_USER_HIS
    - BFM_USER_LAYOUT
    - BFM_USER_PARAMS
    - BFM_USER_PORTAL
    - BFM_USER_PRIV
    - BFM_USER_ROLE
    - BFM_USER_SP
    - BFM_WEAK_PASSWORD
    - GLOBAL_BO
    - GLOBAL_OBJECT
    - GLOBAL_RES
    - ORG_WORK_TIME
    - TFM_SEQUENCES
    - TFM_SERV_LOG
    - TIME_SLICE 
    - TIME_SLICE_GROUP
    - TIME_SLICE_GROUP_ITEM
    - BFM_PORTAL_CHANNEL
    - BFM_PORTAL_INDEX
    - DEF_LANG
    - BANK 
    - ROLE_TYPE
    - SUBS_PRICE_PLAN 
    - PRICE_PLAN_PARAM
    - PRICE_PLAN_TYPE
    - SUBS_PLAN_PRICE
    - TIME_UNIT
    - SUBS_EVENT_TYPE
    - SERV_TYPE_EVENT_RELA
    - STAND_ADDRESS 
    - PROD_SPEC_BS_TEMPLATE
    - AGREEMENT
    - AGREEMENT_ACTION_LIMIT
    - AGREEMENT_APPLY
    - AGREEMENT_GROUP
    - ATTR_POPEDIT
    - AGREEMENT_GROUP_MEMBER
    - AGREEMENT_INSTALLMENT
    - AGREEMENT_LEVEL_ACTION
    - AGREEMENT_NOTIFY
    - AGREEMENT_OBJ
    - AGREEMENT_OBJ_TYPE
    - AGREEMENT_OBJ_TYPE_ACTION
    - AGREEMENT_PENALTY
    - AGREEMENT_PRICE
    - AGREEMENT_QUANTITY_LIMIT
    - AGREEMENT_RELA
    - AGREEMENT_RELA_TYPE
    - AGREEMENT_RSTR
    - AGREEMENT_TYPE
    - AGREEMENT_TYPE_TAG
    - AGREEMENT_VER
    - AGREEMENT_RULE 
    - BUNDLE_MEM_EVENT_RELA
    - BUNDLE_RESTRICT_RULE
    - BUNDLE_RESTRICT_TYPE
    - BUNDLE_USER_MAPPING
    - BUSI_TYPE_DEF
    - BUSI_TYPE_VALUE_DEF
    - COMMON_LANG_OBJ_VALUE
    - CPC_ACCT_ITEM_TYPE_PRIV
    - CPC_AIT_ADD_STAFF
    - CPC_AIT_DEDUCT_STAFF
    - LANGUAGE_TYPE
    - MULTY_LANG_ITEM
    - MULTY_LANG_ITEM_VALUE
    - OFFER_ACCT_ITEM_REL
    - OFFER_ATTR_VALUE
    - OFFER_BUSI_TYPE
    - RES_PROD_SPEC
    - SUBS_EVENT
    - SUBS_EVENT_PROD_STATE_LIMIT
    - SUBS_EVENT_RELA
    - SUBS_RELA_EXCLUSIVE
    - SUBS_RE_EVENT
    - TAG
    - TAG_STYLE
    - TAG_TYPE
    - TARGET_CHOICE_REASION
    - TIMES_LIMIT_RULE
    - TIMES_LIMIT_RULE_APPLY_OBJ   
    - SUBS_EVENT_PROD_STATE_LIMIT
    - BIZ_RULE
    - CONTACT_MAN_ATTR
    - SERVICE_SPEC
    - SERV_TYPE_CFS
    - SERV_SPEC_OPT
    - SERV_SPEC_CATA_MEM
    - SERV_SPEC_CATALOG
    - SERVICE_SPEC_RELA
    - SERVICE_SPEC_ATTR
    - SERVICE_SPEC_ATTR_VALUE
    - SERVICE_TEMPLATE_ATTR
    - SERVICE_TEMPLATE_ATTR_VALUE
    - OFFER_PROMOTION
    - OFFER_PROMO_CATG
    - OFFER_PROMOTION_TYPE
    - OFFER_PROMO_MEMBER
    - OFFER_PROMO_PRICE
    - OFFER_PROMO_GRP
    - OFFER_PROMO_GRP_MEM
    - OFFER_PROMO_FULL_MINUS
    - OFFER_PROMO_MATCH_RULE
    - ORDER_REASON
    - ORDER_REASON_ATTR
    - ORDER_REASON_ATTR_VALUE
    - EXTERNAL_OFFER_MAP
    - OFFER_PRICE_VERSION
    - BUNDLE_SUBS_EVENT_RELA
    - BANK_CARD_TYPE
    - BANK_CARD_TYPE_INST 
    - BATCH_UPDATE_DATA
    - BATCH_UPDATE_TABLE
    - BUSINESS_HOUR
    - BUSINESS_HOUR_TEMPLATE
    - BUSINESS_HOUR_TEMPLATE_DETAIL
    - CUST_FLAG 
    - IBAN_FORMAT
    - SEPA_BANK 
    - TVLOM_ACTIVITY
    - WF_DISPATCH_ORDER_STATE
    - WF_DISPATCH_ORDER_TYPE
    - WF_NODE_FUNCTION
    - WF_NODE_AUTO_FUCTION
    - WF_NODE_FUNCTION
    - WF_NODE_MANUAL_FUCTION
    - WF_WORK_ORDER_STATE
    - BFM_MODULE
    - BFM_PROCESS_ACTIVITY
    - BFM_PROCESS_STATE
    - BUSINESS_MODULE
    - DATA_TYPE
    - INPUT_TYPE
    - SERV_TYPE_CFS_OPT_MAP
    - DOC_TYPE
    
props:
  sql.show: true
  executor.size: 8


