apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpc-web-portal.fullname" . }}
  labels:
    {{- include "cpc-web-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- range .Values.ports }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      {{- end }}
  selector:
    {{- include "cpc-web-portal.selectorLabels" . | nindent 4 }}
---
# Client service for cpc-web-portal.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpc-web-portal.fullname" . }}-outer
  labels:
    {{- include "cpc-web-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.typeouter }}
  ports:
    - port: {{ .Values.service.port }}
      {{- range .Values.ports }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      {{- end }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "cpc-web-portal.selectorLabels" . | nindent 4 }}