apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-mongo
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.type}}
    app: {{.Release.Name}}-mongo
spec:
  ports:
  - port: {{.Values.port.serviceport}}
    targetPort: {{.Values.port.containerport}}
  type: NodePort
  selector:
    app: {{.Release.Name}}-mongo