apiVersion: zalando.org/v1
kind: ClusterKopfPeering
metadata:
  name: default
---
apiVersion: zalando.org/v1
kind: KopfPeering
metadata:
  namespace: {{if .Values.global.namespace}}{{.Values.global.namespace}}{{else}}{{.Release.Name}}-canvas{{end}}
  name: default