apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpc-lifecycle-core.fullname" . }}
  labels:
    {{- include "cpc-lifecycle-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- range .Values.ports }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      {{- end }}
  selector:
    {{- include "cpc-lifecycle-core.selectorLabels" . | nindent 4 }}
