# Default values for cpc-web-product.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 10.45.80.1/dbep/cpc_web_product_r92
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: O_20210209093531

fullnameOverride: cpc-web-product

ports:
  - containerPort: 8080
    protocol: TCP
    name: http

envFrom:
  - configMapRef:
     name: global-config

volumeMounts:
  - mountPath: /tmp/zcore
    name: volume-0
  - mountPath: /tmp/zlogs
    name: volume-1
  - name: cpc-web-product
    mountPath: /opt/ZSMART_HOME/etc
    readOnly: True
  - mountPath: /etc/localtime
    name: zcmlocaltime
  - mountPath: /etc/timezone
    name: zcmtimezone

service:
  type: ClusterIP
  port: 8080

dnsPolicy: ClusterFirst
restartPolicy: Always

volumes:
  - hostPath:
      path: /tmp/zcore
      type: ""
    name: volume-0
  - hostPath:
      path: /tmp/zlogs
      type: ""
    name: volume-1
  - name: cpc-cpcweb-prod
    configMap:
      name: cpc-cpcweb-prod
  - hostPath:
      path: /etc/localtime
      type: ""
    name: zcmlocaltime
  - hostPath:
      path: /etc/timezone
      type: ""
    name: zcmtimezone

cm:
  - name: cpc-web-product
    configMap:
      name: cpc-web-product

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite  /portal-web/cpc(.*)$   /cpc-web/cpc$1 break;
  path: /portal-web/cpc

ingress2:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite  /portal-web/orgstaff(.*)$   /market-web/orgstaff$1 break;
  path: /portal-web/orgstaff

resources:
  limits:
    cpu: "4"
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 512Mi

clusterIP: None