# Default values for apig-operator-uportal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 10.45.80.1/dbep/apig_operator_core
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: M_20210323032227

fullnameOverride: apig-operator-uportal

ports:
  - containerPort: 8080
    protocol: TCP
    name: http

envFrom:
  - configMapRef:
     name: global-config

volumeMounts:
  - mountPath: /tmp/zcore
    name: volume-0
  - mountPath: /tmp/zlogs
    name: volume-1
  - name: apig-all-core
    mountPath: /root/ZSMART_HOME/etc
    readOnly: True
  - mountPath: /etc/localtime
    name: zcmlocaltime
  - mountPath: /etc/timezone
    name: zcmtimezone

service:
  type: ClusterIP
  port: 8080

dnsPolicy: ClusterFirst
restartPolicy: Always

volumes:
  - hostPath:
      path: /tmp/zcore
      type: ""
    name: volume-0
  - hostPath:
      path: /tmp/zlogs
      type: ""
    name: volume-1
  - hostPath:
      path: /etc/localtime
      type: ""
    name: zcmlocaltime
  - hostPath:
      path: /etc/timezone
      type: ""
    name: zcmtimezone

cm:
  - name: apig-all-core
    configMap:
      name: apig-all-core

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /operator/ImportController/importAbilityByJsonFile.do
  path: /portal/apig/api/import/zcm

ingress2:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /operator/dcoos
  path: /dcoos

ingress3:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /operator
  path: /operator

resources:
  limits:
    cpu: "4"
    memory: 4Gi
  requests:
    cpu: 400m
    memory: 1228Mi

clusterIP: None