variables:
  DB_NUM: 4
  TB_NUM: 12

shardingTableRule:
  templates:
    sdst-proj-1:
      actualDataNodes: ds\${0..${DB_NUM - 1}}.${TABLE}\${0..${TB_NUM - 1}}
      databaseStrategy:
        inline:
          shardingColumn: ${DB_COLUMN}
          algorithmExpression: ds\${${DB_COLUMN} % ${DB_NUM}}
      tableStrategy:
        inline:
          shardingColumn: ${TB_COLUMN}
          algorithmExpression: ${TABLE}\${${TB_COLUMN} % ${TB_NUM}}
    sdst-proj-2:
      actualDataNodes: ds\${0..${DB_NUM - 1}}.${TABLE}\${0..${TB_NUM - 1}}
      databaseStrategy:
        inline:
          shardingColumn: ${DB_COLUMN}
          algorithmExpression: ds\${${DB_COLUMN} % ${DB_NUM}}
  usages:
    sdst-proj-1:
      - BAL_SHARE_ITEM_ORDER|ROUTING_ID|PART_ID
      - BAL_SHARE_ORDER|ROUTING_ID|PART_ID
      - BC_MEMBER_ATTR_ORDER|ROUTING_ID|PART_ID
      - BC_MEMBER_ORDER|ROUTING_ID|PART_ID
      - CDR_PRINT_ORDER|ROUTING_ID|PART_ID
      - CREDIT_BALANCE_ORDER|ROUTING_ID|PART_ID
      - CREDIT_LIMIT_ORDER|ROUTING_ID|PART_ID
      - CUST_ORDER|ROUTING_ID|PART_ID
      - CUST_ORDER_ATTR|ROUTING_ID|PART_ID
      - CUST_PROF_ORDER|ROUTING_ID|PART_ID
      - DP_OFFER_ORDER|ROUTING_ID|PART_ID
      - DP_OFFER_ORDER_ATTR|ROUTING_ID|PART_ID
      - FELLOW_NBR_ORDER|ROUTING_ID|PART_ID
      - GOODS_ORDER_ATTR|ROUTING_ID|PART_ID
      - GOODS_ORDER|ROUTING_ID|PART_ID
      - HOME_CELL_ORDER|ROUTING_ID|PART_ID
      - HOME_ZONE_ORDER|ROUTING_ID|PART_ID
      - INDEP_PROD_ORDER_ATTR|ROUTING_ID|PART_ID
      - INDIVIDUAL_LIFECYCLE_ORDER|ROUTING_ID|PART_ID
      - ORDER_ITEM|ROUTING_ID|PART_ID
      - ORDER_ITEM_ATTR|ROUTING_ID|PART_ID
      - ORDER_ITEM_MEMO|ROUTING_ID|PART_ID
      - ORDER_RELA|ROUTING_ID|PART_ID
      - PARALLEL_UPGRADE_ORDER|ROUTING_ID|PART_ID
      - RES_ORDER|ROUTING_ID|PART_ID
      - SIM_CARD_INFO_ORDER|ROUTING_ID|PART_ID
      - SUBS_BASE_ORDER|ROUTING_ID|PART_ID
      - SUBS_BIND_ORDER|ROUTING_ID|PART_ID
      - SUBS_CONTACT_MAN_ORDER|ROUTING_ID|PART_ID
      - SUBS_RELA_ATTR_ORDER|ROUTING_ID|PART_ID
      - BFM_PROCESS_BO|ROUTING_ID|PART_ID
      - WF_DISPATCH_ORDER|ROUTING_ID|PART_ID
      - WF_WORK_ORDER|ROUTING_ID|PART_ID
      - WF_WORK_ORDER_ATTR|ROUTING_ID|PART_ID
      - WF_WORK_ORDER_ACTION|ROUTING_ID|PART_ID
      - WF_WORK_ORDER_HIS|ROUTING_ID|PART_ID
      - TIMER_EVENT|ROUTING_ID|PART_ID
      - TIMER_EVENT_MEMO|ROUTING_ID|PART_ID
      - CUST_ORDER_ATTACH|ROUTING_ID|PART_ID
      - CUST_ORDER_VER|ROUTING_ID|PART_ID
      - CUST_ORDER_VER_ITEM|ROUTING_ID|PART_ID
      - CUST_CONTACT|ROUTING_ID|PART_ID
      - STAFF_DRAFT|ROUTING_ID|PART_ID
      - ORDER_OTC_INST|ROUTING_ID|PART_ID
      - ORDER_OTC_INST_PRICE|ROUTING_ID|PART_ID
      - ORDER_OTC_INST_TAX|ROUTING_ID|PART_ID
      - ORDER_OTC_QRY_BENEFIT|ROUTING_ID|PART_ID
      - ORDER_OTC_QRY_DEPOSIT|ROUTING_ID|PART_ID
      - ORDER_OTC_QRY_ITEM|ROUTING_ID|PART_ID
      - ORDER_OTC_QRY_PRICE|ROUTING_ID|PART_ID
      - ORDER_OTC_QRY_PRICE_ADJUST|ROUTING_ID|PART_ID
      - ORDER_OTC_QRY_TAX|ROUTING_ID|PART_ID
      - ORDER_OTC_INSTALLMENT_PLAN|ROUTING_ID|PART_ID
      - ORDER_OTC_IP_DETAIL|ROUTING_ID|PART_ID
      - ORDER_OTC_TRANSACTION|ROUTING_ID|PART_ID
      - BC_ROLE_ORDER|ROUTING_ID|PART_ID
      - BILL_SPLIT_ORDER|ROUTING_ID|PART_ID
      - GOODS_SALE_ORDER|ROUTING_ID|PART_ID
      - GOODS_SALE_ORDER_ATTR|ROUTING_ID|PART_ID
      - GOODS_SALE_ORDER_COUPON|ROUTING_ID|PART_ID
      - GOODS_SALE_ORDER_DETAIL|ROUTING_ID|PART_ID
      - GOODS_SALE_ORDER_PROMO|ROUTING_ID|PART_ID
      - GOODS_SALE_ORDER_REL|ROUTING_ID|PART_ID
      - GOODS_SALE_ORDER_RES|ROUTING_ID|PART_ID
      - SHOPPINT_CART|ROUTING_ID|PART_ID
      - CART_ITEM|ROUTING_ID|PART_ID
      - CART_ITEM_REL|ROUTING_ID|PART_ID
    sdst-proj-2:
      - WF_DISPATCH_ORDER_ACTION|ROUTING_ID
      - WF_DISPATCH_ORDER_ACTION_ATTA|ROUTING_ID
      - WF_DISPATCH_ORDER_ACTION_ATTR|ROUTING_ID
      - WF_WARN_LOG|ROUTING_ID
      - WF_WARN_DETAIL|ROUTING_ID
      - WF_WORK_ORDER_ACTION_ATTA|ROUTING_ID
      - WF_WORK_ORDER_ACTION_ATTR|ROUTING_ID

shardingRule:
  defaultDatabaseStrategy:
    hint:
      algorithmClassName: com.iwhalecloud.zdaas.jdbc.hint.NameDataBaseHintShardingAlgorithm
  defaultDataSourceName: ds0
  bindingTables:
    - BAL_SHARE_ITEM_ORDER,BAL_SHARE_ORDER,BC_MEMBER_ATTR_ORDER,BC_MEMBER_ORDER,CDR_PRINT_ORDER,CREDIT_BALANCE_ORDER,CREDIT_LIMIT_ORDER,CUST_ORDER,CUST_ORDER_ATTR,CUST_PROF_RDER,DP_OFFER_ORDER,DP_OFFER_ORDER_ATTR,FELLOW_NBR_ORDER,GOODS_ORDER_ATTR,GOODS_ORDER,HOME_CELL_ORDER,HOME_ZONE_ORDER,INDEP_PROD_ORDER_ATTR,INDIVIDUAL_LIFECYCLE_ORDER,ORDER_ITEM,ORDER_ITEM_ATTR,ORDER_ITEM_MEMO,ORDER_RELA,PARALLEL_UPGRADE_ORDER,RES_ORDER,SIM_CARD_INFO_ORDER,SUBS_BASE_ORDER,SUBS_BIND_ORDER,SUBS_CONTACT_MAN_ORDER,SUBS_RELA_ATTR_ORDER,TIMER_EVENT,TIMER_EVENT_MEMO,CUST_ORDER_ATTACH,CUST_ORDER_VER,CUST_ORDER_VER_ITEM,CUST_CONTACT,WF_DISPATCH_ORDER_ACTION,WF_DISPATCH_ORDER_ACTION_ATTA,WF_DISPATCH_ORDER_ACTION_ATTR,WF_WARN_LOG,WF_WARN_DETAIL,WF_WORK_ORDER,WF_WORK_ORDER_ATTR,WF_WORK_ORDER_ACTION_ATTA,WF_WORK_ORDER_ACTION_ATTR,WF_WORK_ORDER_HIS,ORDER_OTC_QRY_PRICE,ORDER_OTC_QRY_PRICE_ADJUST,ORDER_OTC_INSTALLMENT_PLAN,ORDER_OTC_QRY_ITEM,BFM_PROCESS_BO,WF_DISPATCH_ORDER,WF_WORK_ORDER_ACTION

  broadcastTables:
    - ORDER_REASON
    - ORDER_RELA_TYPE
    - ORDER_STATE
    - ORDER_TYPE
    - SUBS_EVENT
    - WF_WORK_ORDER_STATE
    - WF_DISPATCH_ORDER_TYPE
    - TVLOM_ACTIVITY
    - WF_NODE_FUNCTION
    - WF_DISPATCH_ORDER_STATE
    - ALL_SERV_TYPE
    - BUNDLE_COMPOSE_TYPE
    - BUNDLE_UNIT
    - BUNDLE_UNIT_INDEP_PROD_SPEC
    - BUNDLE_UNIT_SUBS_PLAN
    - CATALOG
    - CATG
    - CPC_BUSINESS_MODULE
    - CPC_CONFIG_ITEM
    - CPC_CONFIG_ITEM_PARAM
    - CPC_DATA_TYPE
    - CPC_DOMAIN
    - CPC_INPUT_TYPE
    - CPC_PROJECT
    - DEPEND_PROD_PACKAGE
    - DEPEND_PROD_SPEC
    - GOODS_PROD_PACKAGE
    - GOODS_PROD_SPEC
    - GROUP_TYPE
    - HOT_SALE_TYPE
    - INDEP_PROD_SPEC
    - NETWORK_TYPE
    - OFFER
    - OFFER_APPLY_AREA
    - OFFER_APPLY_CATG
    - OFFER_APPLY_CHANNEL
    - OFFER_APPLY_ORG
    - OFFER_APPLY_ROLE
    - OFFER_APPLY_STAFF
    - OFFER_ATTR
    - OFFER_CATG
    - OFFER_CATG_APPLY_CHANNEL
    - OFFER_CATG_MEM
    - OFFER_GROUP
    - OFFER_GROUP_MEM
    - OFFER_HOT_SALES
    - OFFER_PRICE_DISPLAY
    - OFFER_RELA
    - OFFER_TYPE
    - OFFER_VER
    - PRICE_PLAN
    - PRICE_PLAN_PACKAGE
    - RELA_TYPE
    - SUBS_PLAN
    - SUBS_PLAN_OFFER_ATTR
    - SUBS_PLAN_OFFER_ATTR_VALUE
    - SUBS_PLAN_OFFER_SELECT
    - DOMAIN
    - BFM_AD_CONFIG
    - BFM_APP
    - BFM_AREA
    - BFM_BULLETIN
    - BFM_BULLETIN_LEVEL
    - BFM_BULLETIN_RECIPIENT
    - BFM_BULLETIN_TMPL
    - BFM_BULLETIN_TYPE
    - BFM_BULLETIN_VIEW
    - BFM_COMPONENT_PRIV
    - BFM_DATA_PRIV
    - BFM_DIR
    - BFM_EVENT_CODE
    - BFM_EVENT_SRC
    - BFM_EVENT_TYPE
    - BFM_GROUP_DATA_PRIV
    - BFM_JOB
    - BFM_JOB_LAYOUT
    - BFM_JOB_ROLE
    - BFM_JOB_USER_GROUP
    - BFM_JOB_WORK_TIME
    - BFM_LAYOUT_DEF
    - BFM_LAYOUT_DEF_HIS
    - BFM_MENU
    - BFM_MENU_DIR
    - BFM_MENU_FAVORITE
    - BFM_MVNO_HIS
    - BFM_ORG
    - BFM_ORG_JOB
    - BFM_ORG_TYPE
    - BFM_ORG_WORK_TIME
    - BFM_PARAMS
    - BFM_PART_SP
    - BFM_PORTAL
    - BFM_PORTAL_BIZ_PARAM
    - BFM_PORTAL_MENU
    - BFM_PORTAL_SP
    - BFM_PORTLETS
    - BFM_PORTLET_SCOPE
    - BFM_PORTLET_TYPE
    - BFM_PRIV
    - BFM_PRIV_TYPE
    - BFM_ROLE
    - BFM_ROLE_DATA_PRIV
    - BFM_ROLE_PORTAL
    - BFM_ROLE_PRIV
    - BFM_SECURITY_RULE
    - BFM_SERV_LOG
    - BFM_STAFF
    - BFM_STAFF_GROUP_LEADER_HIS
    - BFM_STAFF_GROUP_RELA
    - BFM_STAFF_HIS
    - BFM_STAFF_JOB
    - BFM_STAFF_ORG
    - BFM_STAFF_ORG_HIS
    - BFM_STAFF_RELA
    - BFM_STAFF_WORK_TIME
    - BFM_TABLE_EXT
    - BFM_TABLE_EXT_VALUE
    - BFM_USER
    - BFM_USER_DATA_PRIV
    - BFM_USER_GRID
    - BFM_USER_GROUP
    - BFM_USER_GROUP_PRIV
    - BFM_USER_HIS
    - BFM_USER_LAYOUT
    - BFM_USER_PARAMS
    - BFM_USER_PORTAL
    - BFM_USER_PRIV
    - BFM_USER_ROLE
    - BFM_USER_SP
    - BFM_WEAK_PASSWORD
    - GLOBAL_BO
    - GLOBAL_OBJECT
    - GLOBAL_RES
    - TFM_EVENT_SRC
    - TFM_EVENT_TYPE
    - TFM_SERV_LOG
    - TFM_SERV_LOG_RELA
    - TIME_SLICE
    - TIME_SLICE_GROUP
    - TIME_SLICE_GROUP_ITEM
    - bfm_portal_channel
    - bfm_portal_index
    - BASE_ATTR
    - TEXT_ATTR
    - ATTR_GROUP_MEM
    - ATTR_GROUP
    - ATTR_VALUE
    - ATTR_VALUE_LINKAGE
    - ATTR_TYPE
    - ATTR_DRIVER
    - ATTR
    - ATTR_APPLY_CATG
    - ATTR_APPLY_CHANNEL
    - ATTR_CATG
    - OBJ_ATTR
    - BFM_PROCESS_ACTIVITY
    - TIME_UNIT
    - SUBS_PRICE_PLAN
    - NP_ORDER_TYPE
    - GLOBAL_OBJECT
    - CONTACT_CHANNEL
    - OPERATION_TYPE
    - RES_TYPE
    - DEF_LANG
    - DRAFT_ORDER_REASON
    - GM_MODEL
    - MEMO_EVENT_TYPE
    - PRICE_PLAN_PARAM
    - PRICE_PLAN_TYPE
    - SUBS_PLAN_PRICE
    - SUBS_EVENT_TYPE
    - SERV_TYPE_EVENT_RELA
    - NP_ORDER
    - NP_ORDER_ITEM
    - AGREEMENT_GROUP_MEMBER
    - AGREEMENT_INSTALLMENT
    - AGREEMENT_LEVEL_ACTION
    - AGREEMENT_NOTIFY
    - AGREEMENT_OBJ
    - AGREEMENT_OBJ_TYPE
    - AGREEMENT_OBJ_TYPE_ACTION
    - AGREEMENT_PENALTY
    - AGREEMENT_PRICE
    - AGREEMENT_QUANTITY_LIMIT
    - AGREEMENT_RELA
    - AGREEMENT_RELA_TYPE
    - AGREEMENT_RSTR
    - AGREEMENT_TYPE
    - AGREEMENT_TYPE_TAG
    - AGREEMENT_VER
    - BUNDLE_MEM_EVENT_RELA
    - BUNDLE_RESTRICT_RULE
    - BUNDLE_RESTRICT_TYPE
    - BUNDLE_USER_MAPPING
    - BUSI_TYPE_DEF
    - BUSI_TYPE_VALUE_DEF
    - COMMON_LANG_OBJ_VALUE
    - CPC_ACCT_ITEM_TYPE_PRIV
    - CPC_AIT_ADD_STAFF
    - CPC_AIT_DEDUCT_STAFF
    - LANGUAGE_TYPE
    - MULTY_LANG_ITEM
    - MULTY_LANG_ITEM_VALUE
    - OFFER_ACCT_ITEM_REL
    - OFFER_ATTR_VALUE
    - OFFER_BUSI_TYPE
    - RES_PROD_SPEC
    - SUBS_EVENT_PROD_STATE_LIMIT
    - SUBS_EVENT_RELA
    - SUBS_RELA_EXCLUSIVE
    - SUBS_RE_EVENT
    - TAG
    - TAG_STYLE
    - TAG_TYPE
    - TARGET_CHOICE_REASION
    - TIMES_LIMIT_RULE
    - TIMES_LIMIT_RULE_APPLY_OBJ
    - SUBS_EVENT_PROD_STATE_LIMIT
    - BIZ_RULE
    - AGREEMENT_RULE
props:
  sql.show: true

