apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog-componentmanager
  labels:
    oda.tmforum.org/componentName: vodafone-productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalog-componentmanager
  template:
    metadata:
      labels:
        app: productcatalog-componentmanager
    spec:
      containers:
      - name: productcatalog-componentmanager
        image: lesterthomas/productcatalog-manager:0.18
        ports:
        - name: pc-regular
          containerPort: 8080