apiVersion: v1
kind: Service
metadata:
  name: mongo-tmf
  labels:
    app: mongo-tmf
    oda.tmforum.org/componentName: vodafone-productcatalog
spec:
  ports:
  - port: 27017
    targetPort: mongo-tmf
    name: mongo-tmf
  type: NodePort
  selector:
    app: mongo-tmf