apiVersion: oda.tmforum.org/v1alpha1
kind: component
metadata:
  name: vodafone-productcatalog
  labels:
    oda.tmforum.org/componentName: vodafone-productcatalog
spec:
  type: productcatalog
  selector:
    matchLabels:
     oda.tmforum.org/componentName: vodafone-productcatalog
  componentKinds:
    - group: core
      kind: Service
    - group: apps
      kind: Deployment  
  version: "0.0.1"
  description: "Vodafone simple reference implementation of ODA Product Catalog." 
  maintainers:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com
  owners:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com   
  coreFunction:
    exposedAPIs: 
    - name: productCatalog
      specification: https://open-api.tmforum.org/TMF620-ProductCatalog-v4.0.0.swagger.json
      implementation: productcatalog
      path: /admin/productCatalogManagement/v2/catalog
      port: 8080
      scopes:
      - name: admin
      - name: regular
    - name: processFlow
      specification: https://open-api.tmforum.org/TMF701-ProcessFlow-v4.0.0.swagger.json
      implementation: camunda
      path: /camunda
      port: 8080
    dependantAPIs: 
    - name: party      
      specification: https://open-api.tmforum.org/TMF632-Party-v4.0.0.swagger.json
  eventNotification:
    publishedEvents:
    - name: Catalog
      href: https://schema.tmforum.org/Product/Catalog.schema.json   
    - name: Category
      href: https://schema.tmforum.org/Product/Category.schema.json
    - name: ProductOffering
      href: https://schema.tmforum.org/Product/ProductOffering.schema.json
    - name: ProductOfferingPrice
      href: https://schema.tmforum.org/Product/ProductOfferingPrice.schema.json
    - name: ProductSpecification
      href: https://schema.tmforum.org/Product/ProductSpecification.schema.json
    - name: Usage
      href: https://schema.tmforum.org/Product/Usage.schema.json
    subscribedEvents:
    - name: ImportJob
      href: https://schema.tmforum.org/Product/ImportJob.schema.json
  management:
  - name: serviceTest
    href: https://manager.local/healthCheck
    specification: https://open-api.tmforum.org/TMF653-ServiceTest-v4.0.0.swagger.json
  - name: alarm
    href: https://manager.local/alarm
    specification: https://open-api.tmforum.org/TMF642-Alarm-v4.0.0.swagger.json
  - name: serviceActivationConfiguration
    href: https://manager.local/serviceConfiguration
    specification: https://open-api.tmforum.org/TMF640-ServiceActivationConfiguration-v4.0.0.swagger.json
  security:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT